default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
        # Common errors
      - id: end-of-file-fixer
        name: Fixing end of file issues

      # Cross platform
      - id: check-case-conflict
        name: Checking for case issues
      - id: mixed-line-ending
        name: Standardizing line endings
        args:
          - --fix=auto

      # Security
      - id: detect-aws-credentials
        name: Ensuring we don't store any AWS Credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        name: Ensuring we don't store any Private Keys
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      # DevOp Hooks
      - id: terraform_fmt
        name: Updating Terraform Code Formatting per Spec
      - id: terraform_docs
        name: Creates Terraform Docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
        name: Checking to Ensure DevOps Best Practices are in Place

      # Security Hooks
      - id: terraform_trivy
        args:
          - >
            --args=--skip-dirs="**/.terraform/**"
            --quiet

  - repo: local
    hooks:
      - id: terraform-validate
        name: Validating Terraform Code Will Compile
        entry: bash -c 'cd terraform && tofu init -upgrade && tofu validate'
        language: system
        types: [terraform]
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/christophmeissner/pytest-pre-commit
    rev: 1.0.0
    hooks:
    - id: pytest
      pass_filenames: false
      entry: uv run pytest -m "not integration"
      always_run: true
      types: [python]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
